import { getDb } from "@/lib/db";
import { settings } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { decryptSecret } from "@/lib/security/crypto";

/**
 * Decrypted AI assistant connection configuration parameters.
 */
export interface AiConfig {
  /** Target API endpoint URL (e.g., 'https://api.openai.com/v1'). */
  apiUrl: string;
  /** Decrypted secret API authentication key. */
  apiKey: string;
  /** Target AI model identifier (e.g., 'gpt-4o', 'claude-3-5-sonnet'). */
  model: string;
  /** Sampling temperature between 0.0 and 2.0. */
  temperature: number;
  /** Master toggle enabling or disabling AI features for the site. */
  enabled: boolean;
}

/**
 * Retrieves and decrypts the site-specific AI integration parameters from SQLite settings.
 *
 * @param siteId - Unique identifier of the tenant site.
 * @returns A Promise resolving to the resolved and decrypted AiConfig object.
 */
export async function getAiConfig(siteId: string): Promise<AiConfig> {
  const db = getDb();
  const rows = db
    .select()
    .from(settings)
    .where(eq(settings.siteId, siteId))
    .all();

  const map = new Map<string, string>();
  for (const r of rows) {
    map.set(r.key, r.value);
  }

  const rawKey = map.get("ai_api_key") || "";
  const decryptedKey = rawKey ? decryptSecret(rawKey) : "";

  return {
    apiUrl: map.get("ai_api_url") || "https://api.openai.com/v1",
    apiKey: decryptedKey,
    model: map.get("ai_model") || "gpt-4o",
    temperature: parseFloat(map.get("ai_temperature") || "0.7"),
    enabled: map.get("ai_enabled") === "true",
  };
}

/**
 * Executes an HTTP chat completion request against any OpenAI-compatible AI API endpoint.
 *
 * @param siteId - Unique identifier of the tenant site owning the AI configuration.
 * @param messages - Array of conversation messages comprising role and text content.
 * @param overrideConfig - Optional partial AI settings to override saved site configuration.
 * @returns A Promise resolving to the text response generated by the language model.
 * @throws {Error} When AI features are disabled, API key is missing, or the upstream API responds with an error code.
 */
export async function callAiChat(
  siteId: string,
  messages: Array<{ role: "system" | "user" | "assistant"; content: string }>,
  overrideConfig?: Partial<AiConfig>
): Promise<string> {
  const baseConfig = await getAiConfig(siteId);
  const config = { ...baseConfig, ...overrideConfig };

  if (!config.enabled && !overrideConfig) {
    throw new Error("AI Assistant is currently disabled in site settings.");
  }
  if (!config.apiKey) {
    throw new Error("No API key configured for OpenAI-compatible endpoint.");
  }

  const cleanUrl = config.apiUrl.replace(/\/+$/, "");
  const endpoint = `${cleanUrl}/chat/completions`;

  const res = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model,
      messages,
      temperature: config.temperature,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`AI API call failed with status ${res.status}: ${errorText}`);
  }

  const json = await res.json();
  return json.choices?.[0]?.message?.content || "";
}
